// navigationTypes.ts
export type RootStackParamList = {
  Splash: undefined;
  Login: undefined;
  Home: undefined;
  DashboardOpd: undefined;
  DashboardIpd: undefined;
  DashboardRed: undefined;
  DashboardYellow: undefined;
  DashboardGreen: undefined;
  AddPatient: undefined;
  AddPatientForm: undefined;
  PatientList: undefined;
  PatientProfile: undefined;
  Tabs: undefined;
  Symptoms: undefined;
  AddSymptoms: undefined;
  Vitals: undefined;
  AddVitals: undefined;
  Reports: undefined;
  AddReports: undefined;
  Doctors: undefined;
  AddDoctors: undefined;
  Prescription: undefined;
  AddMedicineTest: undefined;
  MedicalHistory: undefined;
  EditMedicalHistory: undefined;
MedicalHistoryForm: undefined;
TransferPatient: undefined;
EditPatientProfile: undefined;
AppointmentsList: undefined;
DischargeSummaryDownload: undefined;
  Management: undefined;
  SlotsManagement: undefined;
  HelpScreen: undefined;
  DashboardInfoScreen: undefined;
  TicketsScreen: undefined;
  NewTicketScreen: undefined;
  MyTasks: undefined;
  DashboardPharma: undefined;
  DashboardReception: undefined;
  DashboardLab: undefined;
  DashboardRadio: undefined;
  EmergencyDashboard: undefined;
  Timeline: undefined;
  TimelineRow: undefined;
  PatientListIPD: undefined;
  NotificationScreen: undefined;
  DischargedPatientsIPD: undefined;
  Tests: undefined;
  AddTests: undefined;
  PreviousPrescriptions: undefined;
  TreatmentPlan: undefined;
  RequestSurgeryScreen:undefined;
  HandshakePatientScreen:undefined;
  AlertsScreen:undefined;
  DischargeScreen:undefined;
  PatientRevisitScreen:undefined;
  Pocus:undefined;
  AddPocus:undefined;
  PhysicalExamination:undefined;
  AddPhysicalExamination:undefined;
  AddMedicineScreen:undefined;
  MedicationTimelineScreen:undefined;
  DashboardTriage: undefined
  AddTriageIssue: undefined;
  TriageDialog: undefined;
  TriageFormContext : undefined;
 
  TriageABCD:undefined;
  TriageGCSForm: undefined;
  TriageType:undefined;
  TriageTrauma:undefined;
  TriageNonTrauma:undefined;
  TriageZoneForm: undefined;

  
  OtDashboard:undefined;
  DashboardAlerts:undefined;
  OtInnerTabs: undefined;
  InitialDetails : undefined;
  GeneralPhysicalExamination : undefined;
  Respiratory : undefined;
  Hepato:undefined;
  CardioVascular:undefined;
  Neuro:undefined;
  Renal:undefined;
  Other:undefined;
  ExaminationFindingNotes:undefined;
  Mallampati:undefined;
  PreopControllers: undefined;
  SurgerySchedule: undefined;
  Schedule: undefined;
  AnesthesiaRecordForm : undefined;
  Breathing:undefined;
  Monitors:undefined;
  ConsentForm:undefined;
  PostOpRecordNotes:undefined;


};