// navigationTypes.ts
export type RootStackParamList = {
  Splash: undefined;
  Login: undefined;
  Home: undefined;
  DashboardOpd: undefined;
  DashboardIpd: undefined;
  DashboardRed:undefined;
  DashboardYellow:undefined;
  DashboardGreen:undefined;
  AddPatient: undefined;
  AddPatientForm: undefined;
  PatientList: undefined;
  PatientProfile: undefined;
  Tabs:undefined;
  Symptoms:undefined;
  AddSymptoms:undefined;
  Vitals: undefined;
  AddVitals: undefined;
  Reports: undefined;
  AddReports: undefined;
  Doctors: undefined;
  AddDoctors: undefined;
  Prescription: undefined;
  AddMedicineTest: undefined;
  MedicalHistory : undefined;
  EditMedicalHistory: undefined;
MedicalHistoryForm: undefined;
TransferPatient: undefined;
EditPatientProfile: undefined;
  Management: undefined;
  SlotsManagement: undefined;
  HelpScreen: undefined;
  DashboardInfoScreen: undefined;
  TicketsScreen: undefined;
  NewTicketScreen: undefined;
  MyTasks:undefined;
  DashboardPharma:undefined;
  DashboardReception:undefined;
  DashboardLab:undefined;
  DashboardRadio:undefined;
  EmergencyDashboard:undefined;
};